'use client'
import Link from 'next/link'
import Navbar from '@/components/Navbar'
import { FileText, Shield } from 'lucide-react'
import { useState } from 'react'
import clsx from 'clsx'

type Tab = 'terms' | 'privacy'

export default function TermsPage() {
  const [tab, setTab] = useState<Tab>('terms')

  return (
    <div className="min-h-screen bg-forge-black">
      <Navbar />
      <div className="max-w-3xl mx-auto px-4 py-24 pt-32">

        <div className="text-center mb-10">
          <h1 className="font-display text-4xl text-white mb-2 tracking-wider">LEGAL</h1>
          <p className="text-forge-muted text-sm">Last updated: March 2026</p>
        </div>

        <div className="flex gap-2 bg-forge-dark rounded-xl p-1 mb-8">
          <button onClick={() => setTab('terms')}
            className={clsx('flex-1 flex items-center justify-center gap-2 py-2.5 rounded-lg text-sm font-medium transition-all',
              tab === 'terms' ? 'bg-forge-card text-forge-text' : 'text-forge-muted hover:text-forge-text')}>
            <FileText size={14} /> Terms of Service
          </button>
          <button onClick={() => setTab('privacy')}
            className={clsx('flex-1 flex items-center justify-center gap-2 py-2.5 rounded-lg text-sm font-medium transition-all',
              tab === 'privacy' ? 'bg-forge-card text-forge-text' : 'text-forge-muted hover:text-forge-text')}>
            <Shield size={14} /> Privacy Policy
          </button>
        </div>

        {tab === 'terms' && (
          <div className="card p-8 prose-forge space-y-6 text-sm text-forge-muted leading-relaxed">
            <section>
              <h2 className="text-lg font-semibold text-white mb-3">1. Acceptance of Terms</h2>
              <p>By accessing or using BeatHole AI ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service. These terms apply to all visitors, users, and creators on the platform.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">2. Description of Service</h2>
              <p>BeatHole AI is an AI-powered music creation platform that allows users to generate instrumental beats, edit them in a browser-based studio, and (for Pro subscribers) publish and sell those beats through a digital marketplace with multiple license tiers.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">3. User Accounts</h2>
              <p>You must be at least 16 years old to create an account. You are responsible for maintaining the confidentiality of your account credentials and for all activity under your account. Notify us immediately of any unauthorized access.</p>
              <p className="mt-2">You may not create accounts using automated means, or create multiple accounts to circumvent restrictions. BeatHole reserves the right to suspend or terminate accounts that violate these terms.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">4. AI-Generated Content & Ownership</h2>
              <p>Beats generated through BeatHole AI are created for your personal or commercial use (subject to your subscription plan). You retain ownership of beats you generate. By publishing a beat to the marketplace, you grant BeatHole a non-exclusive license to display, stream, and promote the beat on the platform.</p>
              <p className="mt-2">You are responsible for ensuring your prompts and any uploaded content do not infringe third-party rights. BeatHole is not liable for content generated based on user inputs.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">5. Beat Licensing</h2>
              <p>When a buyer purchases a license, they receive the rights specified in the license tier they purchased. Exclusive licenses transfer primary usage rights to the buyer and the beat is removed from the marketplace. Creators retain moral rights and authorship credit unless waived in an Exclusive license.</p>
              <p className="mt-2">License PDF documents generated by BeatHole constitute the complete licensing agreement between creator and buyer. BeatHole acts as the marketplace facilitator only.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">6. Creator Earnings & Payouts</h2>
              <p>Creators earn 80% of the sale price for each license sold. BeatHole retains a 20% platform fee. Earnings are credited to your account balance after a successful payment. Withdrawals are processed via Stripe Connect and are subject to Stripe's payout timelines and terms. Minimum withdrawal amount is €20.</p>
              <p className="mt-2">BeatHole reserves the right to withhold payouts in cases of suspected fraud, chargebacks, or account violations pending investigation.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">7. Subscriptions & Billing</h2>
              <p>Pro subscriptions are billed monthly. You may cancel at any time; cancellation takes effect at the end of the current billing period. BeatHole does not offer refunds for partial billing periods unless required by applicable law. Prices are subject to change with 30 days' notice.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">8. Prohibited Content</h2>
              <p>You may not use BeatHole to generate, publish, or distribute content that: infringes copyrights or trademarks; promotes illegal activity; is defamatory, harassing, or abusive; violates any applicable law or regulation. BeatHole reserves the right to remove any content at its discretion.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">9. Limitation of Liability</h2>
              <p>BeatHole is provided "as is". To the maximum extent permitted by law, BeatHole disclaims all warranties and shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the platform. Our total liability shall not exceed the amounts you paid to us in the 12 months preceding the claim.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">10. Governing Law</h2>
              <p>These Terms are governed by the laws of the Netherlands. Disputes shall be resolved in the competent courts of the Netherlands, unless mandatory consumer protection laws in your country provide otherwise.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">11. Changes to Terms</h2>
              <p>We may update these Terms at any time. Material changes will be notified via email or a prominent notice on the platform. Continued use after changes constitutes acceptance.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">12. Contact</h2>
              <p>For questions about these Terms, contact us via the <Link href="/support" className="text-forge-accent hover:underline">Support page</Link>.</p>
            </section>
          </div>
        )}

        {tab === 'privacy' && (
          <div className="card p-8 prose-forge space-y-6 text-sm text-forge-muted leading-relaxed">
            <section>
              <h2 className="text-lg font-semibold text-white mb-3">1. Introduction</h2>
              <p>BeatHole AI ("we", "our") is committed to protecting your privacy. This Privacy Policy explains what personal data we collect, how we use it, and your rights under the GDPR (General Data Protection Regulation).</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">2. Data We Collect</h2>
              <ul className="list-disc pl-5 space-y-1">
                <li><strong className="text-forge-text">Account data:</strong> Email address, username, display name, password (hashed).</li>
                <li><strong className="text-forge-text">Profile data:</strong> Bio, avatar URL (optional, user-provided).</li>
                <li><strong className="text-forge-text">Usage data:</strong> Beats generated, prompts used, generation settings, play counts.</li>
                <li><strong className="text-forge-text">Payment data:</strong> Processed by Stripe. We store only your Stripe customer ID, subscription status, and earnings balance. Full card details are never stored by us.</li>
                <li><strong className="text-forge-text">Technical data:</strong> IP address, browser type, access logs (for security and rate limiting).</li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">3. How We Use Your Data</h2>
              <ul className="list-disc pl-5 space-y-1">
                <li>To provide and improve the BeatHole service</li>
                <li>To process payments and manage subscriptions</li>
                <li>To send transactional emails (account confirmation, purchase receipts)</li>
                <li>To detect and prevent fraud and abuse</li>
                <li>To comply with legal obligations</li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">4. Data Sharing</h2>
              <p>We share data only with service providers necessary to operate the platform:</p>
              <ul className="list-disc pl-5 mt-2 space-y-1">
                <li><strong className="text-forge-text">Stripe:</strong> Payment processing and creator payouts.</li>
                <li><strong className="text-forge-text">Stability AI / RunPod:</strong> AI beat generation (prompts and settings sent for processing).</li>
                <li><strong className="text-forge-text">Hosting providers:</strong> Cloud infrastructure for database and file storage.</li>
              </ul>
              <p className="mt-2">We do not sell your personal data to third parties.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">5. Data Retention</h2>
              <p>Account data is retained for as long as your account is active. Deleted accounts have personal data anonymized within 30 days. Beat files and purchase records are retained for 7 years for legal/accounting purposes.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">6. Your Rights (GDPR)</h2>
              <p>You have the right to: access your data, correct inaccuracies, request deletion ("right to be forgotten"), data portability, restrict or object to processing. To exercise these rights, submit a request through the <Link href="/support" className="text-forge-accent hover:underline">Support page</Link>.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">7. Cookies</h2>
              <p>We use only essential cookies for authentication (JWT tokens stored in localStorage). We do not use tracking or advertising cookies.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">8. Security</h2>
              <p>Passwords are hashed using bcrypt. All data is transmitted over HTTPS. Access to production systems is restricted and monitored. Despite our measures, no system is 100% secure — report security issues via Support.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">9. Contact & DPA</h2>
              <p>Data Controller: BeatHole AI. For privacy inquiries or GDPR requests, contact us via the <Link href="/support" className="text-forge-accent hover:underline">Support page</Link>.</p>
            </section>
          </div>
        )}

      </div>
    </div>
  )
}
